### ISSUE TITLE
add docker for centos

### ISSUE THREAD

**Issue by moonming** [iresty/docker-apisix#2]
we can install the rpm directly, for example:
sudo yum install -y https://github.com/iresty/apisix/releases/download/v0.5/apisix-0.5-0.el7.noarch.rpm

**Comment by moonming** [comment]
@vkill I wonder if you are interested in doing this?

**Comment by vkill** [comment]
@moonming We usually compile from source code if it depends docker image that non-system level. maybe it conflicts with system library.

**Comment by moonming** [comment]
what's `non-system level`? the docker image is not `FROM centos:7`?
I am not an expert about docker, so I want to know more details.  I hope it doesn't bother you.

**Comment by vkill** [comment]
> the docker image is not FROM centos:7?
Yes, from [openresty/openresty](https://hub.docker.com/r/openresty/openresty/) 

> what's non-system level?
The system level images include [ubuntu](https://hub.docker.com/_/ubuntu/), [centos](https://hub.docker.com/_/centos/) and more. maybe "non-system level" is not exactly.

**Comment by moonming** [comment]
based on openresty/openresty is not a good idea, APISIX will maintain it's own patches of openresty in the long term.
And compile from source code will introduce many dependencies packages, which are useless for runtime. So I think install openresty and APISIX's rpm packages is good enough.

**Comment by vkill** [comment]
Maybe we should to provide two versions, build from rpm and build from source code, the related docker tags are 0.5-centos7 and master-centos7, what do you think?

**Comment by moonming** [comment]
looks good to me.

**Comment by moonming** [comment]
fixed by https://github.com/iresty/docker-apisix/pull/19
